#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys

sys.path.insert(0, '/usr/lib/wb-mqtt-alice')


import logging
from logging.handlers import SysLogHandler

handler = SysLogHandler(address='/dev/log', facility=SysLogHandler.LOG_USER)
# use logger name as prefix — journald recognizes it as SYSLOG_IDENTIFIER
formatter = logging.Formatter('%(name)s: %(message)s')
handler.setFormatter(formatter)

root_logger = logging.getLogger()
root_logger.setLevel(logging.INFO)
if not any(isinstance(h, SysLogHandler) for h in root_logger.handlers):
    root_logger.addHandler(handler)

logger = logging.getLogger("wb-mqtt-alice-cli")
logger.setLevel(logging.INFO)


from wb_mqtt_alice_cli import main

if __name__ == "__main__":
    sys.exit(main())